### ISSUE TITLE
Issue: Support for array of url params

### ISSUE THREAD

**Issue by rehman-00001** [rehman-00001/qps-utils#1]
Currently, the only url param format supported is this:

http://issuehub.io/?label=bug&label=good+first+issue&language=javascript

If there are duplicate keys, then the last key is considered and the rest of the keys are ignored. 

Ideally, it should be treated as an array of parameters and `parse()` should return the object accordingly.

Example:

```
const params = {
  'name': 'john',
  'color': ['purple', 'orange', 'green']
};

const url = qpsUtils.construct(params); 
// should return this string: 'name=john&color=purple&color=orange&color=green'
```

Also, parsing the url with duplicate keys should return object with the key which has array of values.
 i.e., `qpsUtils.parse(url)`

**Comment by Nicekor** [comment]
Hello, can you give me an example of how you would like it to work with an array?

**Comment by rehman-00001** [comment]
@Nicekor Thanks for your interest in this repo! 
Updated the issue with example!
